---
output: html_document
---
# Basics {#basics}

## Vectors

In R, all data come in vectors. If you type `x = 54.7`, then `x` will be a numeric vector of length 1. Similarly, `y = c("Abc", "xY_z")` is a character vector of length 2. After assigning a vector, you can type its name to see it and use `length` and `class` to see those attributes.

```{r length}
x = c(TRUE, FALSE, TRUE)
length(x)
class(x)
x
```

You can assign with `=` or `<-`. You can even do `c(2,3) -> z`, but this is rare and hard to read in my opinion.



### Classes and types

```{block, type='FOO'}
testing

```

Usually, classes are all we care about in R, and implementation details are not important. However, if you want to know how a variable is stored, you'll want to use `typeof`. For deeper details, peruse [the official documentation](https://cran.r-project.org/doc/manuals/r-release/R-ints.html).

Technical aside: In most programming languages, a *list* means a [linked list](https://en.wikipedia.org/wiki/Linked_list), but in R, it just means a generic vector, containing objects of arbitrary type in each element.

### Slicing and extracting

d

### Sorting

d

### Exercises

d


## Syntax




## Custom functions and CRAN libraries




## Matrices and Arrays

Technical aside: The terminology is a bit weird here. In most programming languages, an *array* is a vector

Warning: drop.

## Randomization



## Loops and Control Flow


## Data frames


