# and some not from SO

## example data

Nontabular data    
  graphs - igraph 
  spatial - http://stackoverflow.com/q/13316185/

Data packages
  see "data sets" section https://cran.r-project.org/web/views/Econometrics.html

  APIs
    (kind of surprised this doesn't have a task view)
    BEA: package bea.R
  
  Just data
    package noncensus
    package Ecdat
    package EconData (not on CRAN, https://github.com/floswald/EconData)

  Mixed with code
    panel data econometrics: package plm
    Achim Zeileis' 'metrics book: package AER

# Date class (cr random folks,  i guess)

    # Jumbled notes

    - `Date`: Stores time as number of days since UNIX epoch on `1970-01-01`. with negative values for earlier dates.
    - It is represented as an integer (however, it is not enforced in the internal representation)
    - They are always printed following the rules of the current Gregorian calendar, even though the calendar was not in use a long time ago. 
    - It doesn't keep track of timezones, so it should not be used to truncate the time out of `POSIXct` or `POSIXlt` objects.
    - `sys.Date()` returns an object of class `Date`

    # More notes
    - [lubridate](https://github.com/hadley/lubridate)'s `ymd`, `mdy`, etc. are alternatives to `as.Date` that also parse to Date class; see [Parsing dates and datetimes from strings with lubridate](http://stackoverflow.com/documentation/r/1157/date-and-time/7018/parsing-dates-and-datetimes-from-strings-with-lubridate).
    - [data.table](https://github.com/Rdatatable/data.table/wiki)'s experimental IDate class is derived from and is mostly interchangeable with Date, but is stored as integer instead of double.

# datetime classes (cr coatless, Alistaire)

    Pitfalls

    With POSIXct, midnight will display only the date and time zone, though the full time is still stored.

    ## Time zones
    - The accepted values of `tz` depend on the location.
        - `CST` is given with `"CST6CDT"` or `"America/Chicago"`
    - For supported locations and time zones use:
        - In R: `OlsonNames()` 
        - Alternatively, try in R: `system("cat $R_HOME/share/zoneinfo/zone.tab")`
    - These locations are given by [Internet Assigned Numbers Authority (IANA)](http://www.iana.org/time-zones) 
        - [List of tz database time zones (Wikipedia)](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
        - [IANA TZ Data (2016e)](http://www.iana.org/time-zones/repository/releases/tzdata2016e.tar.gz) 

# style (relevant for posting to SO)

also useful? dget


    # Prompts

    If you want your code to be copy-pastable, remove prompts such as `R>`, `>`, or `+` at the beginning of each new line. Some Docs authors prefer to not make copy-pasting easy, and that is okay.

    # Console output

    Console output should be clearly distinguished from code. Common approaches include:
    - Include prompts on input (as seen when using the console).
    - Comment out all output, with `#` or `##` starting each line.
    - Print as-is, trusting the leading `[1]` to make the output stand out from the input.
    - Add a blank line between code and console output.

    # Assignment

    `=` and `<-` are fine for assigning R objects. Use white space appropriately to avoid writing code that is difficult to parse, such as `x<-1` (ambiguous between `x <- 1` and `x < -1`)

    # Code comments

    Be sure to explain the purpose and function of the code itself. There isn't any hard-and-fast rule on whether this explanation should be in prose or in code comments. Prose may be more readable and allows for longer explanations, but code comments make for easier copy-pasting. Keep both options in mind.

    # Sections

    Many examples are short enough to not need sections, but if you use them, start with [H1][1].


      [1]: http://stackoverflow.com/editing-help#headers

# making good examples

    Most of the guidance for [creating good examples](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) for Q&A carries over into the documentation. 

    - Make it minimal and get to the point. Complications and digressions are counterproductive.

    - Include both working code and prose explaining it. Neither one is sufficient on its own.

    - Don't rely on external sources for data. Generate data or use the datasets library if possible: 

          library(help = "datasets")

    There are some additional considerations in the context of Docs:

    - Refer to built-in docs like `?data.frame` whenever relevant. The SO Docs are not an attempt to replace the built-in docs. It is important to make sure new R users know that the built-in docs exist as well as how to find them.

    - Move content that applies to multiple examples to the Remarks section.

# na input/output

most fns have args for it

# regex

use perl for lookahead/behind

backslash to escape chars

## Differences from other languages (cr who?)

    Please note that regular expressions in R often look _ever-so-slightly_ different from regular expressions used in other languages.

     - R requires double-backslash escapes (because `"\"` already implies escaping in general in R strings), so, for example, to capture whitespace in most regular expression engines, one simply needs to type `\s`, vs. `\\s` in R. 

     - UTF-8 characters in R should be escaped with a capital U, e.g. `[\U{1F600}]` and `[\U1F600]` match 😀, whereas in, e.g., Ruby, this would be matched with a lower-case u. 

# logicals

`TRUE`, `FALSE` and `NA` are the only values for logical vectors; and all three are reserved words. `T` and `F` can be shorthand for `TRUE` and `FALSE` in a clean R session, but neither `T` nor `F` are reserved, so assignment of non-default values to those names can set users up for difficulties.

xor

# sets

A set contains only one copy of each distinct element. Unlike some other programming languages, base R does not have a dedicated data type for sets. Instead, R treats a vector like a set by taking only its distinct elements. This applies to the set operators, `setdiff`, `intersect`, `union`, `setequal` and `%in%`. For `v %in% S`, only `S` is treated as a set, however, not the vector `v`.

For a true set data type in R, the Rcpp package provides [some options][1].


  [1]: http://stackoverflow.com/a/23015853/
  
## cross products

expand.grid, CJ

outer for special case of two
  
## dupe drop

(note still not a "set", since it has an ordered index)

 # pipery

Pipe operators, available in magrittr and other R packages, build a sequence of operations by passing the result of one step as input for the next step.

Pipe operators, available in `magrittr`, `dplyr`, and other R packages, process a data-object using a sequence of operations by passing the result of one step as input for the next step using infix-operators rather than the more typical R method of nested function calls.

The `magrittr` package also provides several variations of the pipe operator for those who want more flexibility in piping, such as the compound assignment pipe `%<>%`, the exposition pipe `%$%`, and the tee operator `%T>%`. It also provides a suite of alias functions to replace common functions that have special syntax (`+`, `[`, `[[`, etc.) so that they can be easily used within a chain of pipes.

%>% View

pa = . %>% print(nrow = Inf)

define, examine, subset functional sequences

%$% "exposition", <> replacement, T> timeout/branch
  
## syntax

    - lhs %>% rhs    # pipe syntax for `rhs(lhs)`

    - lhs %>% rhs(a = 1)    # pipe syntax for `rhs(lhs, a = 1)`

    - lhs %>% rhs(a = 1, b = .)    # pipe syntax for `rhs(a = 1, b = lhs)`

    - lhs %<>% rhs    # pipe syntax for `lhs <- rhs(lhs)`

    - lhs %$% rhs(a)  # pipe syntax for `with(lhs, rhs(lhs$a))`

    - lhs %T>% rhs  # pipe syntax for `{ rhs(lhs); lhs }`

#








